#!/bin/bash

# choices will be displayed in dmenu
choices="uni\ngmail\nyoutube\ndrive\noverleaf\ngithub\nrtprf\nwg\nluke\ntranslate"

# Your choice in dmenu will determine what xrandr command to run
chosen=$(echo -e $choices | dmenu -i)

case "$chosen" in
    uni) brave https://webmail.maastrichtuniversity.nl
	;;
    gmail) brave https://gmail.com
	;;
    youttube) brave https://youtube.com
	;;
    drive) brave https://drive.google.com
	;;
    overleaf) brave https://overleaf.com
	;;
    github) brave https://github.com/salil-sudo
	;;
    rtprf) brave https://github.com/ccnmaastricht/real_time_pRF
	;;
    wg) brave https://boards.4chan.org/wg/
	;;
    luke) brave https://lukesmith.xyz
	;;
    translate) brave https://translate.google.com
	;;
esac
