#!/bin/bash

# choices will be displayed in dmenu
choices="University\nGmail\nGeneral"

# Your choice in dmenu will determine what xrandr command to run
chosen=$(echo -e $choices | dmenu -i)

case "$chosen" in
    University) printf "salil.bhat@maastrichtuniversity.nl" | sha1sum | awk '{print $1}' | xclip -selection clipboard
  ;;
    Gmail)  printf "phaedo7@gmail.com" | sha1sum | awk '{print $1}' | xclip -selection c
lipboard
 ;;
    General) printf "#Stardust7" | sha1sum | awk '{print $1}' | xclip -selection clipboard
 ;;
esac
